- name: Display OS Release
  hosts: [bastion,allservers]
  gather_facts: no
  become_user: root
  tasks:
    - name: Display OS Release
      shell: cat /etc/os-release
      register: os_release_result
    - name: Print OS Release
      debug:
        var: os_release_result.stdout_lines
