- name: Add Update Secrets
  hosts: [oraclemaster, azuremaster]
  become: yes

  tasks:
    - name: Create directory for resource files
      file:
        path: /tmp/secrets
        state: directory
      when: inventory_hostname == control_node

    - name: Copy YAML content
      copy:
        content: |
          apiVersion: v1
          kind: Secret
          metadata:
            name: db-credentials
          type: Opaque
          data:
            DB_USER: secret
        dest: /tmp/secrets/secrets.yaml
      when: inventory_hostname == control_node
    
    - name: Apply changes to the resource
      command: "kubectl apply -f /tmp/secrets"
      become_user: ubuntu
      when: inventory_hostname == control_node